/**
 * This file is normally generated by:
 *
 *   pnpm supabase:types
 *
 * The stub below keeps TypeScript happy until you've linked the project and
 * generated the real types. Replace it with the auto-generated output.
 */
export type Database = {
  public: {
    /* eslint-disable @typescript-eslint/no-explicit-any */
    Tables: {
      [key: string]: {
        Row: any;
        Insert: any;
        Update: any;
        Relationships: any[];
      };
    };
    Views: {
      [key: string]: {
        Row: any;
        Relationships: any[];
      };
    };
    Functions: {
      [key: string]: {
        Args: any;
        Returns: any;
      };
    };
    /* eslint-enable @typescript-eslint/no-explicit-any */
    Enums: {
      user_role: "admin" | "dispatcher" | "employee";
      customer_type: "residential" | "alltagshilfe" | "commercial";
      shift_status:
        | "scheduled"
        | "in_progress"
        | "completed"
        | "cancelled"
        | "no_show";
      invoice_status: "draft" | "sent" | "paid" | "overdue" | "cancelled";
      notification_channel: "in_app" | "email" | "whatsapp";
    };
  };
};
