-- =============================================================================
-- Default chat channels per org. The redesigned UI groups them under
-- "Kanäle"; the geschäftsleitung channel is private (admin-only join).
--
-- This migration is fully idempotent and ALSO repairs any rows whose slug
-- was mis-generated by the earlier slugify trigger (which turned the '#'
-- prefix into a leading hyphen — slug "-einsatzplan" instead of plain
-- "einsatzplan").
-- =============================================================================

-- ---- 1) Repair the slug trigger so '#' is stripped before slugifying ------
create or replace function public.chat_channels_set_slug()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  base text;
begin
  if new.slug is null or new.slug = '' then
    base := lower(coalesce(new.name, ''));
    -- Drop a leading '#' that channel names typically start with.
    base := regexp_replace(base, '^#+', '');
    -- Replace anything that isn't a-z/0-9 with a hyphen.
    base := regexp_replace(base, '[^a-z0-9]+', '-', 'g');
    -- Collapse runs of hyphens.
    base := regexp_replace(base, '-{2,}', '-', 'g');
    -- Trim leading + trailing hyphens.
    base := regexp_replace(base, '^-|-$', '', 'g');
    new.slug := base;
  end if;
  return new;
end $$;

drop trigger if exists trg_chat_channels_set_slug on public.chat_channels;
create trigger trg_chat_channels_set_slug
  before insert or update on public.chat_channels
  for each row execute function public.chat_channels_set_slug();

-- ---- 2) Backfill existing rows whose slug starts with '-' or has bad shape -
update public.chat_channels
set slug = regexp_replace(
  regexp_replace(
    regexp_replace(lower(coalesce(name, '')), '^#+', ''),
    '[^a-z0-9]+', '-', 'g'
  ),
  '^-|-$', '', 'g'
)
where slug is null
   or slug like '-%'
   or slug like '%-';

-- ---- 3) Seed function — sets slug explicitly so it never depends on the
--        trigger.
create or replace function public.seed_default_chat_channels(org uuid)
returns void language plpgsql security definer set search_path = public as $$
declare
  defaults record;
begin
  for defaults in
    select * from (values
      ('einsatzplan',        'Kanal für Schichtplanung & Vertretungen',     false),
      ('allgemein',          'Alles rund ums Team',                          false),
      ('pflege-alltagshilfe','Alltagshilfe & Pflegekoordination',            false),
      ('finanzen',           'Rechnungen, Lexware & Auswertungen',           false),
      ('geschaeftsleitung',  'Privater Kanal nur für die Geschäftsleitung',  true)
    ) as t(slug, descr, priv)
  loop
    -- Skip when this org already has a channel with this slug (regardless
    -- of how the slug was originally produced).
    if not exists (
      select 1 from public.chat_channels c
      where c.org_id = org and c.slug = defaults.slug
    ) then
      insert into public.chat_channels (
        org_id, name, slug, description, kind, is_direct, is_private, created_by
      ) values (
        org,
        '#' || defaults.slug,
        defaults.slug,
        defaults.descr,
        'channel',
        false,
        defaults.priv,
        null
      );
    end if;
  end loop;
end $$;

-- ---- 4) Backfill every existing org -------------------------------------------
do $$
declare o record;
begin
  for o in select id from public.organizations loop
    perform public.seed_default_chat_channels(o.id);
  end loop;
end $$;

-- ---- 5) Auto-seed on org insert ---------------------------------------------
create or replace function public.trg_seed_default_channels()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  perform public.seed_default_chat_channels(new.id);
  return new;
end $$;

drop trigger if exists trg_organizations_seed_channels on public.organizations;
create trigger trg_organizations_seed_channels
  after insert on public.organizations
  for each row execute function public.trg_seed_default_channels();
